name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  First-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:

    - name: Before Check
      run: ls
      shell: bash

      - name: checkout steps
        uses: actions/checkout@v4

      - name: After check 
        run: ls
        shell: bash